CONNECTALDIR=/opt/connectal
S2H_INTERFACES = CounterRequest:MyCounter.request
H2S_INTERFACES = MyCounter:CounterIndication

BSVFILES = MyCounter.bsv
CPPFILES = testCounter.cpp

include $(CONNECTALDIR)/Makefile.connectal
