CONNECTALDIR=../../connectal
S2H_INTERFACES = CounterRequest:Counter.request
H2S_INTERFACES = Counter:CounterIndication

BSVFILES = Counter.bsv
CPPFILES = testCounter.cpp

include $(CONNECTALDIR)/Makefile.connectal
